### ISSUE TITLE
Resizing columns on table data view triggers error on IE

### ISSUE THREAD

**Issue by mirko77** [ImperialCollegeLondon/EpiCollectplus#101]
Trying to resize a column on IE trigger a `js` error

**Comment by antpuleo2586** [comment]
This error also occurs on chrome and firefox; the error is that "ele.element is undefined".
This code makes no sense anyway, as it's setting the "max-width" on resize, but this is overridden by the fact that the "width" is set on resize. Setting the max-width on resize is redundant.
I should remove the custom code called on resize.

**Comment by mirko77** [comment]
"This code makes no sense anyway" +1
