### ISSUE TITLE
XML upload errors

### ISSUE THREAD

**Issue by antpuleo2586** [ImperialCollegeLondon/EpiCollectplus#103]
1. When creating a project and uploading an xml file, the name of the project is still required, even though it takes this from the xml param: projectName="xxxxxxxxxxx".
2. When opening xml tag has spaces or new lines prepended, we get an error:
   The XML for this project is invalid : simplexml_load_string() [function.simplexml-load-string]: Entity: line 2: parser error : XML declaration allowed only at the start of the document
   We should trim() the xml string before passing to simplexml_load_string()
   Also we should show a more appropriate message to the user, ie "XML not correctly formatted".
3. When I added an xml file and the project name was already taken, there was no check on this until it was too late and I was given the full sql query with the error:
   "INSERT INTO xxxxxx......
   1062 : Duplicate entry 'STRATAA_Demographic_Cencus' for key 'name_UNIQUE'"
   We shouldn't be showing the sql query or error and we should have some error handling in place here, so that the user isn't stuck at a dead end.
   
     Proposed solutions:
   - Use the name entered on creation of the project, as there is an availability check on this
   - Disable the need to name a project on creation when uploading xml, and when duplicate name is       detected, present user with an input field to rename the project

**Comment by mirko77** [comment]
is this all fixed now?
