### ISSUE TITLE
Data too long for column 'keyField' error

### ISSUE THREAD

**Issue by antpuleo2586** [ImperialCollegeLondon/EpiCollectplus#104]
When the input IDs are too long (in my example the length was 49), we get an sql error and original query presented on screen.

We need to handle this error more gracefully, without showing the details of the database tables; we could increase the length of the chars allowed in the column and/or inform users when their input IDs or form names are too long.

**Comment by mirko77** [comment]
we need to modify the database and increase to `varchar(200)` at least

**Comment by mirko77** [comment]
Fixed
