### ISSUE TITLE
G+ redirect after login issue

### ISSUE THREAD

**Issue by antpuleo2586** [ImperialCollegeLondon/EpiCollectplus#105]
Sometimes after logging in via google+, I am redirected here:

http://plus.epicollect.net/http://plus.epicollect.net/

which just gives an error on the page.

Something is happening possibly with the redirect url in the callback.

Will investigate once I can reproduce through set steps.

**Comment by antpuleo2586** [comment]
This occurs when you're already signed into gmail in the browser and click on the 
"Google/Gmail account (OpenID)" link more than once on the epicollect plus login page.
If you click once it's fine so must be something wrong with the handling of multiple requests.
Ideally we want to ignore any subsequent clicks.

**Comment by mirko77** [comment]
Does it happen also on the `relayout` branch?

**Comment by antpuleo2586** [comment]
No, looks good there.

**Comment by mirko77** [comment]
Great! Can we close?

Best,

Mirko

**Comment by antpuleo2586** [comment]
Yeah!
