### ISSUE TITLE
upload to remote server fails

### ISSUE THREAD

**Issue by ucfupas** [ImperialCollegeLondon/EpiCollectplus#131]
Hi,

I am trying to upload the data I collected onto the remote server but since today this is not working anymore. I am using a Motorola moto G smartphone and yesterday the system was upgraded to Android 5.02. before that the upload was working fine but now it does not work. 

thanks for your help

**Comment by mirko77** [comment]
What app are you using? What errors are you getting? What is the project name?

The latest version for Android is this https://play.google.com/store/apps/details?id=uk.ac.imperial.epicollectplus.html5&hl=en_GB

**Comment by ucfupas** [comment]
Hi,

Thanks for the response. After writing the message I tried a few more things and realised that there was a problem with one of the entries. After deleting that entry the issue was resolved.

Thanks again

Pascale

On 3 Nov 2015, at 13:55, Mirko Menegazzo <notifications@github.com<mailto:notifications@github.com>> wrote:

What app are you using? What errors are you getting? What is the project name?

The latest one for Android is this https://play.google.com/store/apps/details?id=uk.ac.imperial.epicollectplus.html5&hl=en_GB

##

**Comment by mirko77** [comment]
Ok, good to know!
