### ISSUE TITLE
Remote server URL not saved in Android App

### ISSUE THREAD

**Issue by walking-the-talk** [ImperialCollegeLondon/EpiCollectplus#136]
I have set up a version of Epicollect+ on my own server and want to link apps on smartphones to that server and upload / download data. 

On the Android version (Beta v1.0.0) the server setting is not saved when I exit the app, so each time I want to load a new project I have to enter the remote server URL again.
Existing projects can sync data with my server, even when the setting is the default server (plus.epicollect.net).
Can this be fixed please? I have tested this on a Fairphone (Android 4.2.2) and a Samsung Galaxy Note II (Android 4.4.2) - I don't know if the same issue occurs with the iOS version of the app as I don't have any Apple equipment.

Many thanks in advance for your help.

**Comment by mirko77** [comment]
Hi, we are aware of the issue you described.

We are currently developing a brand new version of Epicollect so the version you are currently using is not our main focus at the moment. Therefore we cannot give you an estimate when this issue will be solved.

**Comment by walking-the-talk** [comment]
Thanks for the response. I'll hobble along in the meantime. Do you have an estimate of when the new version might be released? Will it be able to import existing projects or would I need to start from scratch?

**Comment by mirko77** [comment]
I reckon before the end of the year.
