### ISSUE TITLE
App not working in Android 6

### ISSUE THREAD

**Issue by josemifv** [ImperialCollegeLondon/EpiCollectplus#139]
Hi all, 

First of all, thanks for the great work. I have installed the server without issues and created a first project with a test form.

Actually, our main problem is that the app for Android does not work in Android > 5 devices, and that is a big issue because we cannot use it for our projects.

I know that you have released EpiCollect 5, and it is a great product for some projects, but for others we need our own server instance because of privacy issues.

At this moment, any help to get EpiCollect+ working will be appreciated

Thanks in advance

J.M.

**Comment by mirko77** [comment]
Hi, this project is not maintained anymore I am afraid. I understand your issue, there are currently two Epicollect+ mobile apps on the Play Store. Are they both not working for you? There is an issue with Epicollect+ Beta not working on 64bit devices and another one with Epicollect+ (old) not loading projects if you do not a physical "Menu" button on the phone. 

We are **NOT** going to solve those issues, our focus is only Epicollect5 at the moment.

**Comment by josemifv** [comment]
Thanks @mirko77 for your response. I understand you are focused now on Epicollect 5. I have tried it and it is a great tool, but for some projects we need a hosted instance of the server and Epicollect 5 server is not available at the moment.

Thanks again for your support.

J.M.
