### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by equidna** [ImperialCollegeLondon/EpiCollectplus#86]
After I followed the server installation steps for epicollect plus, and filled the the database information, I got directed to the url: "http://localhost/epicollectplus/test?redir=true" and got the following error message:

Fatal error: Uncaught exception 'ErrorException' with message 'Array to string conversion' in C:\xampp\htdocs\epicollectplus\main.php:403 Stack trace: #0 [internal function]: handleError(8, 'Array to string...', 'C:\\xampp\\htdocs...', 403, Array) #1 C:\xampp\htdocs\epicollectplus\main.php(403): str_replace('{#dbPermResults...', 'Array', '<!DOCTYPE html>...') #2 C:\xampp\htdocs\epicollectplus\main.php(1051): applyTemplate('base.html', 'testResults.htm...', Array) #3 C:\xampp\htdocs\epicollectplus\main.php(3930): siteTest() #4 {main} thrown in C:\xampp\htdocs\epicollectplus\main.php on line 403

Can anyone help me or have a clue of what is about? I already tried everything and couldn't avoid this error message.
Thank you.

**Comment by mirko77** [comment]
@equidna did you manage to solve it? We are facing the same issue

**Comment by joedixon** [comment]
+1

**Comment by equidna** [comment]
I don't recall exactly what I we've done but basically we had to install the database manually. The SQL script for installing it is somewhere inside the epicollect code, but I don't remember where.

**Comment by SolSeyoum** [comment]
I am facing exactly the same problem. Can anyone tell me how to solve this problem?

**Comment by mirko77** [comment]
it is a problem when using XAMPP latest versions. I installed a LAMP setup manually and it works

**Comment by SolSeyoum** [comment]
Can you tell me how you set up LAMP manually? Thanks!

**Comment by mirko77** [comment]
If you are on Ubuntu  go here https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu, otherwise go here https://www.digitalocean.com/community/tutorials, there are guides for other versions of Linux

**Comment by SolSeyoum** [comment]
I am on Windows 7 64 bit. I there LAMP for Windows 7?

**Comment by mirko77** [comment]
No, in that case you need WAMP Windows-Apache-MySQL-PHP, but install each component manually, not the WAMP package. Look here http://superuser.com/questions/748117/how-to-manually-install-apache-php-and-mysql-on-windows

**Comment by SolSeyoum** [comment]
Dear Mirco,

Thanks for the link and I installed each component manually however it seems I can not establish a connection with mysql database from Epicolletplus. Any idea what could be wrong? I suspect the the error may be from 'httpd.conf'. Thanks for your help.

**Comment by mirko77** [comment]
What is the error?

**Comment by SolSeyoum** [comment]
when I open the site I get this.
![capture](https://cloud.githubusercontent.com/assets/8383827/8603740/6f1eee7e-267a-11e5-8829-7e761a264023.JPG)

**Comment by SolSeyoum** [comment]
and if click home it will open the 'index.html'.

**Comment by mirko77** [comment]
you should actually get a page explaining you what to do next

Best,

Mirko

**Comment by SolSeyoum** [comment]
What kind of page is that? Do you have an example?
 Thanks!

**Comment by mirko77** [comment]
[image: Inline images 1]

which is actually index.html

You probably need to work on your Apache configuration following the
instructions

Best,

Mirko

**Comment by SolSeyoum** [comment]
I found the same error again even if I install the components manually. 
Fatal error: Uncaught exception 'ErrorException' with message 'Array to string conversion' ....

I really don't know what to do now. Any help?

Regards,

**Comment by mirko77** [comment]
As far as I know @equidna was able to solve it

**Comment by mirko77** [comment]
To all facing this problem, now during the installation errors are better handled. The above error is due to the selected user missing required privileges, please refer to the amended installation instructions.
