### ISSUE TITLE
Wrong routing with valid url

### ISSUE THREAD

**Issue by mirko77** [ImperialCollegeLondon/EpiCollectplus#94]
Calling the entry point directly like 

http://plus.epicollect.net/main.php 

gives an error, despite the entry point is perfectly valid

**Comment by antpuleo2586** [comment]
Do you want to allow this file to be called directly? Or redirect access to main.php to index url ( / ) ?

**Comment by mirko77** [comment]
redirect to the home page instead of showing an error

**Comment by mirko77** [comment]
All good
