### ISSUE TITLE
Fatal error: Uncaught exception 'ErrorException' with message 'mysqli::mysqli(): 

### ISSUE THREAD

**Issue by iamrameshkr** [ImperialCollegeLondon/EpiCollectplus#96]
While connecting the project with MYSQL database. I am getting following errors.

Fatal error: Uncaught exception 'ErrorException' with message 'mysqli::mysqli(): (HY000/1045): Access denied for user 'ramesh'@'localhost'

See the screenshot attached . Please help. Thanks in advance.

![1](https://cloud.githubusercontent.com/assets/10753461/8565133/40108800-2570-11e5-9005-33e44dfd2ae5.png)

**Comment by mirko77** [comment]
You have to fix your MySQL permissions, as the error says the access to the
database was denied
