### ISSUE TITLE
Data gathering using The EpiCollect+ mobile app

### ISSUE THREAD

**Issue by iamrameshkr** [ImperialCollegeLondon/EpiCollectplus#99]
Respected Sir,
                      Can we allow the specific users to load the project and gather the data ? Is there any authentication facility so that we can restrict the unauthorised users.

**Comment by mirko77** [comment]
you can set the project as private and hidden from the home page, so only users who know the name of the project will be able to download it. We currently do not offer grain control on which user can or cannot upload data, we will introduce that on the next big release.

If that is not enough for you, have a look at our friend GeoKey. (http://geokey.org.uk/) 

Last time I checked they offered grain control on user access, and you will still be using Epicollect+ mobile apps to collect data. 

Android: https://play.google.com/store/apps/details?id=uk.ac.imperial.epicollectplus.html5&hl=en_GB

iOS: https://itunes.apple.com/us/app/epicollect+/id999309173?ls=1&mt=8
